name: linting, testing, bulding
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2

      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: install modules
        run: npm install

      - name: build prodaction project
        run: npm run build:prod

      - name: linting ts
        run: npm run lint:ts

      - name: linting scss
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit